config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  resources :categories, except: [:new, :show]
  resources :titles
  resources :quizzes, except: [:index]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :titles
  validates :name, presence: true, uniqueness: true
end

app/models/quiz.rb
class Quiz < ApplicationRecord
  belongs_to :title
  validates :title, :question, :answer1, :answer2, :answer3, :answer4, :answer, presence: true
end

app/models/title.rb
class Title < ApplicationRecord
  belongs_to :category
  has_many :quizes
  validates :title, :category, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def new
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  def new
  end

  def index
  end

  def show
  end

  def edit
  end
end

app/controllers/titles_controller.rb
class TitlesController < ApplicationController
  def index
  end

  def new
  end

  def edit
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/helpers/titles_helper.rb
module TitlesHelper
end

app/views/categories/new.html.erb
<h1>Categories#new</h1>
<p>Find me in app/views/categories/new.html.erb</p>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="mt-3 mx-auto">
      <h1>セルフクイズ</h1>
      <p>学習用問題作成・解答サイトです。</p>
      <p class="text-center"><%= link_to '問題を解く', categories_path, class: "btn btn-outline-dark px-5" %></p>
      <p class="text-center"><%= link_to '問題を作る', new_title_path, class: "btn btn-outline-dark px-5" %></p>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SelfQuiz</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/quizzes/edit.html.erb
<h1>Quizzes#edit</h1>
<p>Find me in app/views/quizzes/edit.html.erb</p>

app/views/quizzes/index.html.erb
<h1>Quizzes#index</h1>
<p>Find me in app/views/quizzes/index.html.erb</p>

app/views/quizzes/new.html.erb
<h1>Quizzes#new</h1>
<p>Find me in app/views/quizzes/new.html.erb</p>

app/views/quizzes/show.html.erb
<h1>Quizzes#show</h1>
<p>Find me in app/views/quizzes/show.html.erb</p>

app/views/titles/edit.html.erb
<h1>Titles#edit</h1>
<p>Find me in app/views/titles/edit.html.erb</p>

app/views/titles/index.html.erb
<h1>Titles#index</h1>
<p>Find me in app/views/titles/index.html.erb</p>

app/views/titles/new.html.erb
<h1>Titles#new</h1>
<p>Find me in app/views/titles/new.html.erb</p>

app/views/titles/show.html.erb
<h1>Titles#show</h1>
<p>Find me in app/views/titles/show.html.erb</p>